name: New Thought Workflow

on:
  repository_dispatch:
    types: [new_thought]

permissions:
  contents: write

jobs:
  process-new-thought:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            # We need a token with write permissions to push back to the repo
            token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Create new thought file
        run: |
          # Extract data from the event payload
          TITLE=$(jq -r '.client_payload.title' "$GITHUB_EVENT_PATH")
          CONTENT=$(jq -r '.client_payload.content' "$GITHUB_EVENT_PATH")
          DATE=$(jq -r '.client_payload.date' "$GITHUB_EVENT_PATH")
          FILENAME=$(jq -r '.client_payload.filename' "$GITHUB_EVENT_PATH")

          # Create the markdown file content
          thought_content=$(cat <<EOF
---
date: "$DATE"
title: "$TITLE"
---

$CONTENT
EOF
          )
          # Write the new thought file
          echo "$thought_content" > "thoughts/$FILENAME"
          echo "Created new thought file: thoughts/$FILENAME"
      
      - name: Install dependencies
        run: npm install

      - name: Build thoughts index
        run: node scripts/build-index.js
      
      - name: Generate HTML files for thoughts
        run: |
          for md_file in thoughts/*.md; do
            if [ -f "$md_file" ]; then
              html_file="thoughts/$(basename "$md_file" .md).html"
              if [ ! -f "$html_file" ]; then
                cp thought.html "$html_file"
                echo "Created HTML file: $html_file"
              fi
            fi
          done

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add thoughts/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "feat: add new thought - '$TITLE'"
            git push
          fi 